### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PashaKagan** [Mikaciu/WinSCPSiteConfigurationToFileZilla#1]
Hey,
Are you still supporting this? 
I tried running it, and it results in an empty file (just the XML structure, no content).

**Comment by Mikaciu** [comment]
Hello, 
I'm afraid I can't do much without at least some details : what versions of WinSCP & Filezilla are you using ? On which system ?

**Comment by PashaKagan** [comment]
Hey,
WinSCP 5.11.2 and FileZilla 3.28.0 on Win10 x64. 

After running the tool on a WinSCP.ini file, I'm getting sitemanager.xml which includes the following:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<FileZilla3>
  <Servers/>
</FileZilla3>
```

Thanks for taking the time to reply!

**Comment by Mikaciu** [comment]
Hello, 

I just gave it a shot with an export from WinSCP 5.11.2 without any issue. 

Could you please send me your WinSCP ini file (obfuscating server hostnames & passwords) _via_ private message ?

**Comment by PashaKagan** [comment]
How do I send a private message here? Couldn't find an option.
Also, how do I obfuscate? The file is 1820-lines-long... :)

**Comment by Mikaciu** [comment]
To obfuscate, you would have to replace anything that's after "hostname=" by something innocuous, like "host.name".
I'm afraid there is no private way on github to communicate ; could you please create an account on https://framapad.org/ ? Then I'll give you access.

**Comment by PashaKagan** [comment]
Hey,
Please send me a quick mail - I'll reply with the file. Much more effective than opening up a new account :)

**Comment by Mikaciu** [comment]
Could you please check again ? Commit #5ff6ca1 should solve the issue.

**Comment by PashaKagan** [comment]
Seems to be working now! :)
