### ISSUE TITLE
May We create a php converter from this?

### ISSUE THREAD

**Issue by ttodua** [Mikaciu/WinSCPSiteConfigurationToFileZilla#3]
Hi.
Nice works.
However, java works only for machines where it is installed, and not on shared hostings (where .php is supported).

Is there any way to create php code instead of java? Where can we see a source-code, or will you be able to create it?

**Comment by Mikaciu** [comment]
Hello, 

Thanks ! 

I retrieved the JAR from [another project](https://github.com/YuriMB/WinSCP-Password-Recovery), through I think it may be possible to do it in PHP ...

**Comment by ttodua** [comment]
thanks. last question, your java main class seems protected/encrypted. why?

**Comment by Mikaciu** [comment]
I guess you would have to ask @YuriMB ...

**Comment by YuriMB** [comment]
Hi :).

There is nothing encrypted / protected. The full source is in my repo: https://github.com/YuriMB/WinSCP-Password-Recovery/blob/master/src/main/java/Main.java. The password storage routine from WinSCP itself ís encrypted though. That was the entire point of the project. I searched through the source of WinSCP, and created similar routines in Java, to provide me with my real passwords.

My code is free as in free beer. Do with it what you want. Good luck @tazotodua !

**Comment by ttodua** [comment]
YuriMB, thanks! i know, your repository code is open-source. One problem I've faced is that it couldnt decrypt current WINSCP version encrypted passwords :( probably something messed up on my side..

**Comment by YuriMB** [comment]
Hi Tazotodua, I've checked the most recent version of the WinSCP source code, and although they have made a few changes to the encryption, they appear to be cosmetic (function renames, etc). So I think that the code should still work.
